name: MazePay
version: 2.0.0
api: [5.0.0]
author: PixelMCN & MazecraftMCN Team
main: PixelMCN\MazePay\MazePay
description: A lightweight, fully customizable PocketMine economy plugin
load: STARTUP

permissions:
  mazepay.command.balance:
    description: Allows users to view their balance
    default: true
  mazepay.command.pay:
    description: Allows users to pay others
    default: true
  mazepay.command.bank:
    description: Allows users to open the bank menu
    default: true
  mazepay.command.deposit:
    description: Allows users to deposit money
    default: true
  mazepay.command.withdraw:
    description: Allows users to withdraw money
    default: true
  mazepay.command.rich:
    description: Allows users to view top balances
    default: true
  mazepay.command.addbalance:
    description: Allows operators to add money to a player
    default: op
  mazepay.command.removebalance:
    description: Allows operators to remove money from a player
    default: op
  mazepay.command.setbalance:
    description: Allows operators to set a player's balance
    default: op
  mazepay.command.help:
    description: Shows help for all commands
    default: true
