# MazePay Configuration File
# Author: PixelMCN & MazecraftMCN Team

# Database Configuration
# Types: sqlite, mysql, json
database:
  type: sqlite
  
  # MySQL Settings (used when type is mysql)
  mysql:
    host: localhost
    port: 3306
    username: root
    password: ""
    database: mazepay

# Economy Settings
economy:
  # Currency symbol (e.g., $, €, ¥, etc.)
  currency-symbol: "$"
  
  # Starting balance for new players
  starting-balance:
    wallet: 1000
    bank: 0
  
  # Bank interest rate (percentage per login/interval)
  # Set to 0 to disable interest
  interest-rate: 0.5
  
  # Minimum amount for transactions
  minimum-transaction: 1
  
  # Maximum wallet capacity (set to -1 for unlimited)
  max-wallet: -1
  
  # Maximum bank capacity (set to -1 for unlimited)
  max-bank: -1

# Performance Settings
performance:
  # Enable caching for faster balance lookups
  enable-cache: true
  
  # Cache lifetime in seconds
  cache-lifetime: 300
  
  # Save interval in ticks (20 ticks = 1 second)
  save-interval: 6000

# Form Settings
forms:
  # Enable custom images in forms
  enable-images: true
  
  # Image URLs (leave empty for no image)
  images:
    bank-menu: "textures/blocks/gold_block"
    deposit: "textures/items/gold_ingot"
    withdraw: "textures/items/emerald"
    balance: "textures/items/diamond"
    pay: "textures/items/emerald"

# Logging
logging:
  # Log all transactions
  log-transactions: true
  
  # Log admin actions
  log-admin-actions: true
